language: python
env:
  global:
    - TZ=UTC
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
install:
  - pip install codecov
  - pip install -r requirements
script:
  coverage run -m tests.tests
after_success:
  codecov
