language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=timestring tests/tests.py
after_success:
  - coveralls
